export const START_CLOCK = 'STARTCLOCK';
export const PAUSE_CLOCK = 'PAUSECLOCK';
export const RESET_CLOCK = 'RESETCLOCK';
export const RESUME_CLOCK = 'RESUMECLOCK';
export const SET_TIME_REMAINING = 'SETTIMEREMAINING';